<script id="popper-js" src="assets/js/popper.min.js"></script>
<script id="bootstrap-js" src="assets/js/bootstrap.min.js"></script>
<script id="bootstrap-dropdown-js" src="assets/js/bootstrap-dropdown-ml-hack.min.js"></script>
<script id="swiper-slider-js" src="assets/js/swiper-bundle.min.js"></script>
<script id="parallaxie-js" src="assets/js/parallaxie.js"></script>
<script id="imagesloaded-js" src="assets/js/imagesloaded.min.js"></script>
<script id="isotope-js" src="assets/js/isotope.pkgd.min.js"></script>
<script id="parallax-scroll-js" src="assets/js/parallax-scroll.js"></script>
<script id="wow-js" src="assets/js/wow.min.js"></script>
<script id="countdown-js" src="assets/js/countdown.js"></script>
<script id="marquee-js" src="assets/js/jquery.marquee.min.js"></script>
<script id="cursor-bundle-js" src="assets/js/cursor-bundle.js"></script>
<script id="magnific-popup-js" src="assets/js/magnific-popup.min.js"></script>
<script id="appear-js" src="assets/js/appear.min.js"></script>
<script id="odometer-js" src="assets/js/odometer.min.js"></script>
<script id="circularProgressBar-js" src="assets/js/circularProgressBar.min.js"></script>
<script id="techco-main-js" src="assets/js/main.js"></script>
<script src="assets/js/search-index.js"></script><script src="assets/js/static.js"></script>